spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: miao1314B
    url: jdbc:mysql://localhost:3306/srm

  redis:
    host: localhost
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        min-idle: 0
    connect-timeout: 1000